"""Shared data models for the multi-agent content pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass(slots=True)
class ResearchChunk:
    """A normalized research record stored in shared memory."""

    chunk_id: str
    title: str
    content: str
    source_url: str
    published_at: str | None = None


@dataclass(slots=True)
class ResearchBrief:
    """Research package passed from the Researcher to the Writer."""

    topic: str
    chunks: list[ResearchChunk] = field(default_factory=list)


@dataclass(slots=True)
class DraftArticle:
    """Draft article generated by the Writer and refined later."""

    topic: str
    markdown: str


@dataclass(slots=True)
class SeoMetadata:
    """SEO metadata generated by the SEO Optimizer."""

    seo_title: str
    meta_description: str
    target_keywords: list[str]
    heading_suggestions: list[str]
    keyword_density: dict[str, float]


@dataclass(slots=True)
class PipelineResult:
    """Final result returned after publication."""

    topic: str
    output_path: str
    markdown: str
    metadata: SeoMetadata
    created_at: datetime
    extras: dict[str, Any] = field(default_factory=dict)
